### ISSUE TITLE
Improve the root experience

### ISSUE THREAD

**Issue by olofbokedal** [oddhill/drupal-oddprofile#10]
IMO the default admin toolbar is way to big and I really miss the dropdown behavior for quicker navigation. Perhaps https://www.drupal.org/project/admin_toolbar together with https://www.drupal.org/project/toolbar_themes could to the trick?

Might also be worth to test https://www.drupal.org/project/coffee and see if it's something that could make the navigation even faster?

(Copied from https://github.com/oddhill/drupal-starter-kit/issues/13)

**Comment by NormySan** [comment]
I think we should add the admin toolbar and have all of the modules it provides installed by default when creating a new site from the profile.

But, i think we should stick with the default theme provided by the admin toolbar module since it's built with accessibility in mind and i think it's nicer from the end users point of view (but this is just pure speculation).

We should definitely try the coffee module and see if it performs well :)

**Admin toolbar with all modules enabled**

![admin-toolbar-all-modules](https://user-images.githubusercontent.com/3884281/34601566-d1f5b4f6-f1fc-11e7-875a-b891d2b281fd.png)

**Comment by NormySan** [comment]
Most of these modules are installed except coffee.

**Comment by NormySan** [comment]
Coffee has also been added as a module so I will close this issue since all modules have been added.
